#!/usr/bin/env sh

set -e

setup/install-homebrew
setup/link-dotfiles


info "Running all setup scripts..."
for setup in tag-*/setup; do
  dir=$(basename "$(dirname "$setup")")
  info "Running setup for ${dir#tag-}..."
  . "$setup"
done
